### ISSUE TITLE
Events - Add AGU and other workshops

### ISSUE THREAD

**Issue by erinmr** [NASA-Openscapes/NASA-Openscapes.github.io#2]
Ask DAAC Cohort for ideas on other events like IMPACT workshop to add to event page. Note to add the AGU workshop if it is accepted.

**Comment by erinmr** [comment]
Also would like to add Carpentries Instructor training even though it is closed to document it happened.

**Comment by jules32** [comment]
I added the science champions too – we could also say we'll be looking for teams to nominate
