### ISSUE TITLE
Add Upcoming Events

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/NASA-Openscapes.github.io#20]
From @ScienceCat18 https://github.com/NASA-Openscapes/NASA-Openscapes.github.io/pull/19#issuecomment-1765372918

## add Upcoming Events
e.g. AGU FM DAAC workshop and all other relevant presentations/activities? Or was the idea to have recent past events on the "home/welcome" front page?

**Comment by ScienceCat18** [comment]
Add link to the Workshop description and registration page? If people come across it and are interested, they can more easily navigate to register :) TY
https://agu.confex.com/agu/fm23/meetingapp.cgi/Session/193427

**Comment by stefaniebutland** [comment]
@ScienceCat18 How does this look?
https://nasa-openscapes.github.io/
![Screenshot 2023-10-20 at 11 00 02 AM](https://github.com/NASA-Openscapes/NASA-Openscapes.github.io/assets/11927811/4e6de20f-9f23-4251-bc01-134da112a9b1)

I'm happy to make any edits!

**Comment by stefaniebutland** [comment]
@jules32  is good for now; can we close?
