### ISSUE TITLE
Add project media/news 

### ISSUE THREAD

**Issue by erinmr** [NASA-Openscapes/NASA-Openscapes.github.io#3]
* [Openscapes](https://www.openscapes.org/blog/2021/03/10/nasa-announcement/ ) and [NCEAS](https://www.nceas.ucsb.edu/news/nasa-openscapes)
* [Metadata Game Changers](https://metadatagamechangers.com/blog/2021/3/10/metadata-game-changers-partners-with-openscapes-in-new-nasa-funded-project)
* [EarthData Blog](https://earthdata.nasa.gov/learn/articles/openscapes)

**Comment by jules32** [comment]
Shall we do this as a static media page with a list like openscapes.org/media, or a blog? 

When we're ready, would a blog be good here too for more technical pieces, and we can cross-post bigger posts at openscapes.org and earthdata blog?

**Comment by erinmr** [comment]
Updated our events page with those links and caught up with current events.
