### ISSUE TITLE
Replace twitter with Mastodon in header?

### ISSUE THREAD

**Issue by jonthegeek** [NASA-Openscapes/NASA-Openscapes.github.io#33]
There's a link to the Openscapes Twitter/X account in the header, but that account hasn't posted since May and references https://fosstodon.org/@openscapes (which I'm happy to see is the actually active account).  Putting that URL with `icon: mastodon` (in place of [lines 33-34 of _quarto.yml](https://github.com/NASA-Openscapes/NASA-Openscapes.github.io/blob/8097f58e5fe7ff4a417ab7b756e11e86587c1191/_quarto.yml#L33-L34)) should do the trick, if there isn't a reason I'm not aware of to keep it as-is. I can submit a quick PR if it's ok to do so!

**Comment by jules32** [comment]
Hello @jonthegeek, yes, thank you! A PR would be welcome :)
