### ISSUE TITLE
Add SEDAC presentations to About page

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/NASA-Openscapes.github.io#42]
Add the slides and recording times/ links for these awesome talks

https://zenodo.org/records/10523525

https://www.youtube.com/watch?v=apinEk9PM_4

Bri: 1:31
Cassie: 3:19
Carl: around 3:55:08

**Comment by jules32** [comment]
Hi @BriannaLind would this be something you'd be able to do?

**Comment by BriannaLind** [comment]
Yeah - should I add a link to Carl's presentation also?

**Comment by BriannaLind** [comment]
I can do it, I can use the practice :)

**Comment by jules32** [comment]
Thanks Bri! Yes Carl's presentation would be great to include

**Comment by BriannaLind** [comment]
So I was about to commit .... but then I realized our slides all link to the google drive.  I guess it would be better to point to zenodo?

**Comment by jules32** [comment]
I would link to google slides, then in parentheses have a url to (zenodo) and you would (youtube).

Thinking: 
- main purpose is for ourselves. Google slides let us reuse easily
- second purpose is for open community more broadly. Link to the bigger picture via zenodo.

**Comment by BriannaLind** [comment]
AHHH good idea! I'll do that now :)
