### ISSUE TITLE
Why NASA/Why Openscapes

### ISSUE THREAD

**Issue by erinmr** [NASA-Openscapes/NASA-Openscapes.github.io#5]
Suggesting we move blog text over to the site: 
Why NASA? Why Openscapes?
We are getting these questions a lot, so here is our take.

NASA Earth Science Data Systems missions collect Earth data, including sea ice, physical oceanography, vegetation and many other parameters – data used by researchers around the world for many different purposes, including answering pressing questions in ecology and environmental science. Further, NASA promotes open science – from the NASA Earth Science Data Systems (ESDS) program 2020 Highlights report:

Open data are the foundation of ESDS efforts to fulfill the program’s vision of accelerating scientific advancement for societal benefit through innovative Earth science data stewardship and technology development…. [This includes a specific goal] to leverage the diversity of global Earth science communities to advance open science.

Openscapes’ long-term goal is to enable robust, inclusive, and enduring science- and data-driven solutions to global and time-sensitive challenges. We approach open science as a spectrum, as a behavior change, and as a movement. We see data analysis and stewardship as entryways to meet scientists where they are, helping them develop new skill sets and mindsets while empowering them as leaders. With NASA support, the project team and the partners, the Openscapes Framework fundamentally changes the paradigm for supporting research teams and DAAC mentors, first to work more openly with their teams on the cloud, and ultimately to advance open science!

**Comment by jules32** [comment]
Done: https://nasa-openscapes.github.io/about.html#why-nasa-why-openscapes
